### ISSUE TITLE
Basic auth is not sent to registry with different domain

### ISSUE THREAD

**Issue by MrNocTV** [Joxit/docker-registry-ui#284] opened 2023-01-16 04:38 UTC
Hi, I use this docker registry UI and I have an issue...

## Bug description

I use `registry.com` domain for the backend `registry:2` and `registry-ui.com` for the `docker-registry-ui`.
After login on browser (browser shows a simple username/password form, it is closed after I successfully login with the `registry:2`.
But after that, requests to `registry-ui.com` get 401, I check the request headers, there is no fields regarding authorization or authentication.

## Expected behavior

I think even though the domain is different, it should work because I have specified the registry url in the config file.

**Comment by kubal5003** [comment] 2023-02-23 12:18
I also experienced this behaviour today and hence decided to deploy this on the same domain, but this has its own issues unfortunately.

**Comment by Joxit** [comment] 2023-03-10 03:30
Hi, thank you for using my project and submitting issues :smile: 

Is your issue linked to this question from the FAQ ?
> -   Why OPTIONS (aka preflight requests) and DELETE fails with 401 status code (using Basic Auth) ?
>     -   This is caused by a bug in docker registry, it returns 401 status requests on preflight requests, this breaks [W3C preflight-request specification](https://www.w3.org/TR/cors/#preflight-request). I suggest to have your UI on the same domain than your registry e.g. registry.example.com/ui/ **or** use `NGINX_PROXY_PASS_URL` **or** configure a nginx/apache/haproxy in front of your registry that returns 200 on each OPTIONS requests. (see [#104](https://github.com/Joxit/docker-registry-ui/issues/104), [#204](https://github.com/Joxit/docker-registry-ui/issues/204), [#207](https://github.com/Joxit/docker-registry-ui/issues/207), [#214](https://github.com/Joxit/docker-registry-ui/issues/214), [#266](https://github.com/Joxit/docker-registry-ui/issues/266)).

If this is the case, and as I said in almost all linked issues, this is a docker registry issue and it's not a part of my project. You may override the OPTION response from your registry (via your reverse proxy) and return a status code 200 instead of 401.
The UI itself cannot solve this issue...

**Comment by alexanderwolz** [comment] 2023-05-18 06:35
Hi @MrNocTV 

I also experience kind of the same behavior. I solved this by setting up my proxy to serve all registry requests on the same domain. For example:
- registry.com/ui -> joxit/docker-registry-ui:2.4.1 (with ```NGINX_PROXY_PASS_URL```)
- registry.com/v2 -> registry:2.8.2
- registry.com/auth -> keycloak/keycloak:21.1.1 (redirect with CORS to authserver.com/*/protocol/docker-v2/auth)

So finally Safari and Firefox are working nicely now, but I have issues with Chrome and need to re-authenticate on every click. Maybe the description in #303  would help you?

How is your authentication setup in registry? via token or htpasswd?

**Comment by MrNocTV** [comment] 2023-06-01 02:03
@alexanderwolz 
I couldn't find a solution so I have changed to use this repo instead 
https://github.com/klausmeyer/docker-registry-browser

**Comment by alexanderwolz** [comment] 2023-06-01 06:12
Hi @MrNocTV 
That project looks nice, too.

I have also started a side project for one of my customers using Angular and Bootstrap. It reduces HTTP traffic by caching tokens and tags. I recently published it as open source at https://github.com/alexanderwolz/registry-angular-ui (see also the images at [Docker Hub](https://hub.docker.com/r/alexanderwolz/registry-angular-ui))

You are welcome to check it out.

**Comment by Joxit** [comment] 2023-06-01 06:37
Hi @MrNocTV  and @alexanderwolz , I'm sad to see you go to different projects.

@alexanderwolz I've checked your project, it's a nice one and thank you for the credit :smile:  Are you not afraid of the security breaches that [storing passwords in local storage can cause](https://stackoverflow.com/questions/7859972/storing-credentials-in-local-storage)? I had also thought about it but I found that the risk was too great. :thinking:

**Comment by alexanderwolz** [comment] 2023-06-01 07:01
Hi @Joxit 

It was a requirement to have a login screen and I also thought about it for a long time. I ended up saving the credentials base64 encoded with a valid period of 2h in a Token object that is encrypted with [CryptoJS](https://cryptojs.gitbook.io/docs/) AES encryption and put in the local storage.

At least this approach works fine on all browsers whereas the Basic Auth approach does not work on Chrome (see #303 ) for my client's configuration. Basic auth struggles with 301 redirects on certain browsers.

**Comment by Joxit** [comment] 2023-06-07 07:08
Okay I see, you are encoding the basic auth in your fronted with a secret. Good choice ^^

Yeah I did respond to your #303 issue, since I didn't succeed to reproduce your bug I wanted you to host an example but I didn't get a response and well... You preferred to create your own project instead.

Since the original issue here didn't get a response too and choose another project, I will close it.

**Closed** 2023-06-07 07:09 UTC
